---
abstract: 'Create objects on the fly'
author:
  - 'Robert Norris <rob@eatenbyagrue.org>'
build_requires:
  Scalar::Util: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Object-Anon
requires:
  Exporter: '0'
  overload: '0'
resources:
  bugtracker: https://github.com/robn/Object-Anon/issues
  repository: git://github.com/robn/Object-Anon.git
version: '0.001'
